### ISSUE TITLE
Debugging nodeJS javascript on VS22

### ISSUE THREAD

**Issue by miken2c** [sayedihashimi/todojswebapp#3] opened 2024-09-29 14:21 UTC
Hello i'm reading your post on devblogs, i also work with javascript on Visual Studio but its being a bad experience because of this issue:

https://developercommunity.visualstudio.com/t/A-way-to-disable-dynamic-debugging-on-ja/10755149

How i could disable the [dynamic] thing when working with pure nodejs and not web?

**Comment by sayedihashimi** [comment] 2024-09-30 20:23
@miken2c I have converted the Suggestion to a Feedback ticket. Suggestion Tickets are when a new feature is requested. In this case, I think this is better as a Feedback ticket. The ticket is in the correct area for my team to pick this up. We can follow up on the ticket.

**Comment by miken2c** [comment] 2024-09-30 22:58
@sayedihashimi  thankyou!! im following.

**Comment by sayedihashimi** [comment] 2024-10-01 00:05
Closing this here because we will use the Feedback ticket to track the progress. The team should pick this up in a day or two for the initial triage.

**Closed by sayedihashimi** 2024-10-01 00:05 UTC

**Comment by miken2c** [comment] 2024-10-01 15:27
@sayedihashimi could you also tag the team responsible for **Image Watch**?

I mean this:
https://developercommunity.visualstudio.com/t/Open-source-Image-Watch-plugin/351613?ref=blog.brianrandell.com

It's labeled "on roadmap" for **years** theres close 100 upvotes and a lot of people requesting it but they never replied anymore.

**Comment by juancesx** [comment] 2024-12-10 04:35
@sayedihashimi we didn't receive any comment anymore on the community site.
Could you please update us with any news?

**Comment by sayedihashimi** [comment] 2024-12-10 17:25
@joj do you know the current status of https://developercommunity.visualstudio.com/t/A-way-to-disable-dynamic-debugging-on-ja/10755149?

**Comment by joj** [comment] 2024-12-10 17:27
We know what the issue is. We don't have a fix yet.
